// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CopyBufferMain

#include_with_pragmas "MirisThreadGroupSize.hlsl"

StructuredBuffer<uint> _sourceBuffer;
RWStructuredBuffer<uint> _destBuffer;

int _Length;
int _SrcOffset;
int _DestOffset;

[numthreads(THREADS_PER_GROUP,1,1)]
void CopyBufferMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x < (unsigned int)_Length) {
        _destBuffer[id.x + _DestOffset] = _sourceBuffer[id.x + _SrcOffset];
    }
}