#pragma kernel ConvertBufferMain

Texture2D<float> _sourceBuffer;
Texture2D<float> _eccLutTexture; // 256x256 R8
RWStructuredBuffer<float> _destBuffer;

uint _AllocationLength;
uint _AllocationOffset;
uint _SrcMosaicStride;
uint _SrcMosaicOffset;
uint _SrcMosaicTileWidth;
uint _SrcMosaicTileHeight;
uint _SrcMosaicTileX;
uint _SrcMosaicTileY;
uint _SrcMosaicInterleaveType;
uint _SrcMosaicTextureWidth;
uint _SrcMosaicTextureHeight;
float _SrcMosaicMin;
float _SrcMosaicMax;
uint _srcNumSplats;
uint _SrcIsSHColor;
uint _IsRangeNormalized;
int _EccPart; // 0 <= none, 1 = part1, 2 = part2

float convertSH0ToColor(float dc0)
{
    float kSH_C0 = 0.2820948f;
    return dc0 * kSH_C0 + 0.5f;
}

void unpack(int readLocation)
{
    uint y = readLocation / _SrcMosaicTileWidth;
    uint x = readLocation - y * _SrcMosaicTileWidth;
    
    const uint xmin = _SrcMosaicTileX * _SrcMosaicTileWidth;
    const uint ymin = _SrcMosaicTileY * _SrcMosaicTileHeight;
    y += ymin;
    x += xmin;
    
    float dataPoint = _sourceBuffer.Load(int3(x, y, 0));
    if(_IsRangeNormalized == 0){   
        if (_SrcIsSHColor != 0)
        {
            dataPoint = convertSH0ToColor(dataPoint);
        }
        _destBuffer[_AllocationOffset + readLocation * _SrcMosaicStride + _SrcMosaicOffset] = dataPoint;
        return;
    }
    
    const float range = _SrcMosaicMax - _SrcMosaicMin;
    float valueDecoded = 0;
    
    float valueForCombining = 0.0f;
    if (_SrcMosaicInterleaveType == 0)
    {
        if(_EccPart == 1){
            valueDecoded = dataPoint;
        }
        else if(_EccPart == 2){
            uint part1 = _destBuffer[_AllocationOffset + readLocation * _SrcMosaicStride + _SrcMosaicOffset] * 255.0;
            uint part2 = dataPoint * 255.0;
            valueDecoded = _eccLutTexture.Load(int3(part2, part1, 0)).r;
        }else{
            valueDecoded = dataPoint;
        }
    }
    else if(_SrcMosaicInterleaveType == 1)
    {
        // on CPU side order of draw calls will be first high bits then low bits
        valueForCombining = _destBuffer[_AllocationOffset + readLocation * _SrcMosaicStride + _SrcMosaicOffset];
        uint highBits = uint(valueForCombining * 255) & 0xff;
        uint lowBits = uint(dataPoint * 255) & 0xff;
        uint combinedBits = (highBits << 8) | lowBits;
        valueDecoded = combinedBits / 65535.0f;
        valueDecoded = valueDecoded * range + _SrcMosaicMin;
    }
    else
    {
        valueDecoded = dataPoint * range + _SrcMosaicMin;
    }
    
    if (_SrcIsSHColor != 0)
    {
        valueDecoded = convertSH0ToColor(valueDecoded);
    }
    
    _destBuffer[_AllocationOffset + readLocation * _SrcMosaicStride + _SrcMosaicOffset] = valueDecoded;
}

[numthreads(1024,1,1)]
void ConvertBufferMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x < _srcNumSplats)
    {
        unpack(id.x);
    }
}