//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Packages/com.miris.sdk.extras/Runtime/Controls and Navigation/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Miris.Runtime
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Packages/com.miris.sdk.extras/Runtime/Controls and Navigation/PlayerInputActions.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @PlayerInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""34de8009-eb8e-4dfc-9fda-93ca97952d74"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""41caa933-72f6-4aaf-b711-b3f079e3368d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LookAround"",
                    ""type"": ""Value"",
                    ""id"": ""a486e7a8-aa11-4f7a-acef-cd073acb29ab"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""EnableLookAround"",
                    ""type"": ""Value"",
                    ""id"": ""ea3d3568-2501-493a-9e48-803f8a8c2cf7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MinMaxUserInterface"",
                    ""type"": ""Button"",
                    ""id"": ""6679fc80-df92-40a8-a3ab-d148a49ce719"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MinMaxDeveloperInterface"",
                    ""type"": ""Button"",
                    ""id"": ""1ca674fa-8e82-41eb-8783-2cd19ccfa294"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MinMaxTimelineInterface"",
                    ""type"": ""Button"",
                    ""id"": ""f82ab157-6d53-495d-af8d-a726a40b3806"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttemptTeleport"",
                    ""type"": ""Button"",
                    ""id"": ""d7126425-aa8d-4225-8326-b93e5f37d0d8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttemptClearScene"",
                    ""type"": ""Button"",
                    ""id"": ""89d88f8d-f7c2-4de1-ad85-dc01cbf8593f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwapCameras"",
                    ""type"": ""Button"",
                    ""id"": ""1bf6478d-f00e-44b1-a526-a9cad084e188"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WSAD"",
                    ""id"": ""fb4cc318-dd48-4a0b-9e34-9220253a645d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fcaceb14-de11-4eb8-822d-31d47da0d832"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2e0703c8-3685-417f-80fc-13cdc7e8ee3c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""63751017-d20d-4b3a-a00c-4237e9cb1552"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9c3ba8f0-cd95-4a87-8632-d75b35476238"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e8e429ad-a002-427c-924f-e328e52bd8c5"",
                    ""path"": ""<OculusTouchController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c822af8-9aa6-43d0-9575-c7f315e05d0c"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.1,y=0.1)"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72c488a1-5a68-421d-bec1-b162c8b71e0e"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookAround"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""017653d8-f07a-4375-8a10-9959a8cf20a9"",
                    ""path"": ""<OculusTouchController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookAround"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b65bf04-ce5c-4e1e-a072-dd47c734fffa"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableLookAround"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4a14c38-1749-4de2-a71e-835a4699e353"",
                    ""path"": ""<OculusTouchController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableLookAround"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bdba096-19fd-41da-908a-54cfa693a708"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinMaxUserInterface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""834251ca-cc67-4326-b1bf-43d95462d512"",
                    ""path"": ""<OculusTouchController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinMaxUserInterface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""093ac1c5-88c4-4e73-99ab-437f53e3942f"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinMaxUserInterface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18c1eebe-c637-4d97-bf75-a87dd77b645a"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinMaxDeveloperInterface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b083f82-63f1-4bbf-9732-e17a136bdc7e"",
                    ""path"": ""<OculusTouchController>{LeftHand}/{GripButton}"",
                    ""interactions"": ""Hold(duration=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinMaxDeveloperInterface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b59ed7da-f5fe-49a6-b859-6c44e4e99838"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinMaxTimelineInterface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a709183d-c0ac-4c3e-97ad-53a01f75d56d"",
                    ""path"": ""<OculusTouchController>{LeftHand}/primaryButton"",
                    ""interactions"": ""Hold(duration=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinMaxTimelineInterface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21b6171a-1662-4487-b990-e0646385ec75"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttemptTeleport"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c697fb21-9261-42df-8404-ca87f17f7b11"",
                    ""path"": ""<XRController>{RightHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttemptTeleport"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4dca370-9072-4c66-b35a-36563a6ef5b5"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttemptClearScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e979ab6e-c3e8-465a-907c-a97e114f4a6f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttemptClearScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""788855d4-6e4c-4ac2-a870-4006b945dcf4"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapCameras"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a3358ae-0112-4ae1-8e42-23b485881abb"",
                    ""path"": ""<XRController>{LeftHand}/{PrimaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapCameras"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""id"": ""4b5aa0ac-00fa-4228-8313-c91d4344ee70"",
            ""actions"": [
                {
                    ""name"": ""PrimaryTouchStart"",
                    ""type"": ""Value"",
                    ""id"": ""288f46ba-6ac7-4fe4-9696-4cad4a149a8b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryTouchButton"",
                    ""type"": ""Button"",
                    ""id"": ""1b322d2f-26b3-44fa-b723-e6178877709d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTouchStart"",
                    ""type"": ""Value"",
                    ""id"": ""5b6f5dc4-99ad-4fd5-967d-008b8d0b7a3c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryTouchButton"",
                    ""type"": ""Button"",
                    ""id"": ""9580ce18-48bf-4454-aa25-78f2b603e371"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e9049a23-c9ac-40cc-848a-6f889b8ebdb8"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d6c36a6-3669-4293-b717-8123262c42bd"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97173816-ccda-4438-8cc0-e1dd8972ca5f"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6660d8f7-53b7-4f2f-b565-71feaac3280f"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
            m_Player_LookAround = m_Player.FindAction("LookAround", throwIfNotFound: true);
            m_Player_EnableLookAround = m_Player.FindAction("EnableLookAround", throwIfNotFound: true);
            m_Player_MinMaxUserInterface = m_Player.FindAction("MinMaxUserInterface", throwIfNotFound: true);
            m_Player_MinMaxDeveloperInterface = m_Player.FindAction("MinMaxDeveloperInterface", throwIfNotFound: true);
            m_Player_MinMaxTimelineInterface = m_Player.FindAction("MinMaxTimelineInterface", throwIfNotFound: true);
            m_Player_AttemptTeleport = m_Player.FindAction("AttemptTeleport", throwIfNotFound: true);
            m_Player_AttemptClearScene = m_Player.FindAction("AttemptClearScene", throwIfNotFound: true);
            m_Player_SwapCameras = m_Player.FindAction("SwapCameras", throwIfNotFound: true);
            // Touch
            m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
            m_Touch_PrimaryTouchStart = m_Touch.FindAction("PrimaryTouchStart", throwIfNotFound: true);
            m_Touch_PrimaryTouchButton = m_Touch.FindAction("PrimaryTouchButton", throwIfNotFound: true);
            m_Touch_SecondaryTouchStart = m_Touch.FindAction("SecondaryTouchStart", throwIfNotFound: true);
            m_Touch_SecondaryTouchButton = m_Touch.FindAction("SecondaryTouchButton", throwIfNotFound: true);
        }

        ~@PlayerInputActions()
        {
            UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, PlayerInputActions.Player.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Touch.enabled, "This will cause a leak and performance issues, PlayerInputActions.Touch.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player
        private readonly InputActionMap m_Player;
        private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
        private readonly InputAction m_Player_Move;
        private readonly InputAction m_Player_LookAround;
        private readonly InputAction m_Player_EnableLookAround;
        private readonly InputAction m_Player_MinMaxUserInterface;
        private readonly InputAction m_Player_MinMaxDeveloperInterface;
        private readonly InputAction m_Player_MinMaxTimelineInterface;
        private readonly InputAction m_Player_AttemptTeleport;
        private readonly InputAction m_Player_AttemptClearScene;
        private readonly InputAction m_Player_SwapCameras;
        /// <summary>
        /// Provides access to input actions defined in input action map "Player".
        /// </summary>
        public struct PlayerActions
        {
            private @PlayerInputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Player/Move".
            /// </summary>
            public InputAction @Move => m_Wrapper.m_Player_Move;
            /// <summary>
            /// Provides access to the underlying input action "Player/LookAround".
            /// </summary>
            public InputAction @LookAround => m_Wrapper.m_Player_LookAround;
            /// <summary>
            /// Provides access to the underlying input action "Player/EnableLookAround".
            /// </summary>
            public InputAction @EnableLookAround => m_Wrapper.m_Player_EnableLookAround;
            /// <summary>
            /// Provides access to the underlying input action "Player/MinMaxUserInterface".
            /// </summary>
            public InputAction @MinMaxUserInterface => m_Wrapper.m_Player_MinMaxUserInterface;
            /// <summary>
            /// Provides access to the underlying input action "Player/MinMaxDeveloperInterface".
            /// </summary>
            public InputAction @MinMaxDeveloperInterface => m_Wrapper.m_Player_MinMaxDeveloperInterface;
            /// <summary>
            /// Provides access to the underlying input action "Player/MinMaxTimelineInterface".
            /// </summary>
            public InputAction @MinMaxTimelineInterface => m_Wrapper.m_Player_MinMaxTimelineInterface;
            /// <summary>
            /// Provides access to the underlying input action "Player/AttemptTeleport".
            /// </summary>
            public InputAction @AttemptTeleport => m_Wrapper.m_Player_AttemptTeleport;
            /// <summary>
            /// Provides access to the underlying input action "Player/AttemptClearScene".
            /// </summary>
            public InputAction @AttemptClearScene => m_Wrapper.m_Player_AttemptClearScene;
            /// <summary>
            /// Provides access to the underlying input action "Player/SwapCameras".
            /// </summary>
            public InputAction @SwapCameras => m_Wrapper.m_Player_SwapCameras;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="PlayerActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="PlayerActions" />
            public void AddCallbacks(IPlayerActions instance)
            {
                if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @LookAround.started += instance.OnLookAround;
                @LookAround.performed += instance.OnLookAround;
                @LookAround.canceled += instance.OnLookAround;
                @EnableLookAround.started += instance.OnEnableLookAround;
                @EnableLookAround.performed += instance.OnEnableLookAround;
                @EnableLookAround.canceled += instance.OnEnableLookAround;
                @MinMaxUserInterface.started += instance.OnMinMaxUserInterface;
                @MinMaxUserInterface.performed += instance.OnMinMaxUserInterface;
                @MinMaxUserInterface.canceled += instance.OnMinMaxUserInterface;
                @MinMaxDeveloperInterface.started += instance.OnMinMaxDeveloperInterface;
                @MinMaxDeveloperInterface.performed += instance.OnMinMaxDeveloperInterface;
                @MinMaxDeveloperInterface.canceled += instance.OnMinMaxDeveloperInterface;
                @MinMaxTimelineInterface.started += instance.OnMinMaxTimelineInterface;
                @MinMaxTimelineInterface.performed += instance.OnMinMaxTimelineInterface;
                @MinMaxTimelineInterface.canceled += instance.OnMinMaxTimelineInterface;
                @AttemptTeleport.started += instance.OnAttemptTeleport;
                @AttemptTeleport.performed += instance.OnAttemptTeleport;
                @AttemptTeleport.canceled += instance.OnAttemptTeleport;
                @AttemptClearScene.started += instance.OnAttemptClearScene;
                @AttemptClearScene.performed += instance.OnAttemptClearScene;
                @AttemptClearScene.canceled += instance.OnAttemptClearScene;
                @SwapCameras.started += instance.OnSwapCameras;
                @SwapCameras.performed += instance.OnSwapCameras;
                @SwapCameras.canceled += instance.OnSwapCameras;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="PlayerActions" />
            private void UnregisterCallbacks(IPlayerActions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @LookAround.started -= instance.OnLookAround;
                @LookAround.performed -= instance.OnLookAround;
                @LookAround.canceled -= instance.OnLookAround;
                @EnableLookAround.started -= instance.OnEnableLookAround;
                @EnableLookAround.performed -= instance.OnEnableLookAround;
                @EnableLookAround.canceled -= instance.OnEnableLookAround;
                @MinMaxUserInterface.started -= instance.OnMinMaxUserInterface;
                @MinMaxUserInterface.performed -= instance.OnMinMaxUserInterface;
                @MinMaxUserInterface.canceled -= instance.OnMinMaxUserInterface;
                @MinMaxDeveloperInterface.started -= instance.OnMinMaxDeveloperInterface;
                @MinMaxDeveloperInterface.performed -= instance.OnMinMaxDeveloperInterface;
                @MinMaxDeveloperInterface.canceled -= instance.OnMinMaxDeveloperInterface;
                @MinMaxTimelineInterface.started -= instance.OnMinMaxTimelineInterface;
                @MinMaxTimelineInterface.performed -= instance.OnMinMaxTimelineInterface;
                @MinMaxTimelineInterface.canceled -= instance.OnMinMaxTimelineInterface;
                @AttemptTeleport.started -= instance.OnAttemptTeleport;
                @AttemptTeleport.performed -= instance.OnAttemptTeleport;
                @AttemptTeleport.canceled -= instance.OnAttemptTeleport;
                @AttemptClearScene.started -= instance.OnAttemptClearScene;
                @AttemptClearScene.performed -= instance.OnAttemptClearScene;
                @AttemptClearScene.canceled -= instance.OnAttemptClearScene;
                @SwapCameras.started -= instance.OnSwapCameras;
                @SwapCameras.performed -= instance.OnSwapCameras;
                @SwapCameras.canceled -= instance.OnSwapCameras;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />.
            /// </summary>
            /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
            public void RemoveCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
            /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
            /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
            public void SetCallbacks(IPlayerActions instance)
            {
                foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="PlayerActions" /> instance referencing this action map.
        /// </summary>
        public PlayerActions @Player => new PlayerActions(this);

        // Touch
        private readonly InputActionMap m_Touch;
        private List<ITouchActions> m_TouchActionsCallbackInterfaces = new List<ITouchActions>();
        private readonly InputAction m_Touch_PrimaryTouchStart;
        private readonly InputAction m_Touch_PrimaryTouchButton;
        private readonly InputAction m_Touch_SecondaryTouchStart;
        private readonly InputAction m_Touch_SecondaryTouchButton;
        /// <summary>
        /// Provides access to input actions defined in input action map "Touch".
        /// </summary>
        public struct TouchActions
        {
            private @PlayerInputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public TouchActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Touch/PrimaryTouchStart".
            /// </summary>
            public InputAction @PrimaryTouchStart => m_Wrapper.m_Touch_PrimaryTouchStart;
            /// <summary>
            /// Provides access to the underlying input action "Touch/PrimaryTouchButton".
            /// </summary>
            public InputAction @PrimaryTouchButton => m_Wrapper.m_Touch_PrimaryTouchButton;
            /// <summary>
            /// Provides access to the underlying input action "Touch/SecondaryTouchStart".
            /// </summary>
            public InputAction @SecondaryTouchStart => m_Wrapper.m_Touch_SecondaryTouchStart;
            /// <summary>
            /// Provides access to the underlying input action "Touch/SecondaryTouchButton".
            /// </summary>
            public InputAction @SecondaryTouchButton => m_Wrapper.m_Touch_SecondaryTouchButton;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Touch; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="TouchActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="TouchActions" />
            public void AddCallbacks(ITouchActions instance)
            {
                if (instance == null || m_Wrapper.m_TouchActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_TouchActionsCallbackInterfaces.Add(instance);
                @PrimaryTouchStart.started += instance.OnPrimaryTouchStart;
                @PrimaryTouchStart.performed += instance.OnPrimaryTouchStart;
                @PrimaryTouchStart.canceled += instance.OnPrimaryTouchStart;
                @PrimaryTouchButton.started += instance.OnPrimaryTouchButton;
                @PrimaryTouchButton.performed += instance.OnPrimaryTouchButton;
                @PrimaryTouchButton.canceled += instance.OnPrimaryTouchButton;
                @SecondaryTouchStart.started += instance.OnSecondaryTouchStart;
                @SecondaryTouchStart.performed += instance.OnSecondaryTouchStart;
                @SecondaryTouchStart.canceled += instance.OnSecondaryTouchStart;
                @SecondaryTouchButton.started += instance.OnSecondaryTouchButton;
                @SecondaryTouchButton.performed += instance.OnSecondaryTouchButton;
                @SecondaryTouchButton.canceled += instance.OnSecondaryTouchButton;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="TouchActions" />
            private void UnregisterCallbacks(ITouchActions instance)
            {
                @PrimaryTouchStart.started -= instance.OnPrimaryTouchStart;
                @PrimaryTouchStart.performed -= instance.OnPrimaryTouchStart;
                @PrimaryTouchStart.canceled -= instance.OnPrimaryTouchStart;
                @PrimaryTouchButton.started -= instance.OnPrimaryTouchButton;
                @PrimaryTouchButton.performed -= instance.OnPrimaryTouchButton;
                @PrimaryTouchButton.canceled -= instance.OnPrimaryTouchButton;
                @SecondaryTouchStart.started -= instance.OnSecondaryTouchStart;
                @SecondaryTouchStart.performed -= instance.OnSecondaryTouchStart;
                @SecondaryTouchStart.canceled -= instance.OnSecondaryTouchStart;
                @SecondaryTouchButton.started -= instance.OnSecondaryTouchButton;
                @SecondaryTouchButton.performed -= instance.OnSecondaryTouchButton;
                @SecondaryTouchButton.canceled -= instance.OnSecondaryTouchButton;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="TouchActions.UnregisterCallbacks(ITouchActions)" />.
            /// </summary>
            /// <seealso cref="TouchActions.UnregisterCallbacks(ITouchActions)" />
            public void RemoveCallbacks(ITouchActions instance)
            {
                if (m_Wrapper.m_TouchActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="TouchActions.AddCallbacks(ITouchActions)" />
            /// <seealso cref="TouchActions.RemoveCallbacks(ITouchActions)" />
            /// <seealso cref="TouchActions.UnregisterCallbacks(ITouchActions)" />
            public void SetCallbacks(ITouchActions instance)
            {
                foreach (var item in m_Wrapper.m_TouchActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_TouchActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="TouchActions" /> instance referencing this action map.
        /// </summary>
        public TouchActions @Touch => new TouchActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
        public interface IPlayerActions
        {
            /// <summary>
            /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMove(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LookAround" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLookAround(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "EnableLookAround" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnEnableLookAround(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "MinMaxUserInterface" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMinMaxUserInterface(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "MinMaxDeveloperInterface" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMinMaxDeveloperInterface(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "MinMaxTimelineInterface" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMinMaxTimelineInterface(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "AttemptTeleport" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAttemptTeleport(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "AttemptClearScene" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAttemptClearScene(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "SwapCameras" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSwapCameras(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Touch" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="TouchActions.AddCallbacks(ITouchActions)" />
        /// <seealso cref="TouchActions.RemoveCallbacks(ITouchActions)" />
        public interface ITouchActions
        {
            /// <summary>
            /// Method invoked when associated input action "PrimaryTouchStart" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPrimaryTouchStart(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "PrimaryTouchButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPrimaryTouchButton(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "SecondaryTouchStart" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSecondaryTouchStart(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "SecondaryTouchButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSecondaryTouchButton(InputAction.CallbackContext context);
        }
    }
}
