//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Packages/com.miris.app_kit/Runtime/Navigation/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Miris.Runtime
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Packages/com.miris.app_kit/Runtime/Navigation/PlayerInputActions.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @PlayerInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""XR"",
            ""id"": ""34de8009-eb8e-4dfc-9fda-93ca97952d74"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""41caa933-72f6-4aaf-b711-b3f079e3368d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LookAround"",
                    ""type"": ""Value"",
                    ""id"": ""a486e7a8-aa11-4f7a-acef-cd073acb29ab"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""EnableLookAround"",
                    ""type"": ""Value"",
                    ""id"": ""ea3d3568-2501-493a-9e48-803f8a8c2cf7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MinMaxUserInterface"",
                    ""type"": ""Button"",
                    ""id"": ""6679fc80-df92-40a8-a3ab-d148a49ce719"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MinMaxDeveloperInterface"",
                    ""type"": ""Button"",
                    ""id"": ""1ca674fa-8e82-41eb-8783-2cd19ccfa294"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AttemptClearScene"",
                    ""type"": ""Button"",
                    ""id"": ""89d88f8d-f7c2-4de1-ad85-dc01cbf8593f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WSAD"",
                    ""id"": ""fb4cc318-dd48-4a0b-9e34-9220253a645d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""fcaceb14-de11-4eb8-822d-31d47da0d832"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2e0703c8-3685-417f-80fc-13cdc7e8ee3c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""63751017-d20d-4b3a-a00c-4237e9cb1552"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9c3ba8f0-cd95-4a87-8632-d75b35476238"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e8e429ad-a002-427c-924f-e328e52bd8c5"",
                    ""path"": ""<OculusTouchController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c822af8-9aa6-43d0-9575-c7f315e05d0c"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.1,y=0.1)"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72c488a1-5a68-421d-bec1-b162c8b71e0e"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookAround"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""017653d8-f07a-4375-8a10-9959a8cf20a9"",
                    ""path"": ""<OculusTouchController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookAround"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b65bf04-ce5c-4e1e-a072-dd47c734fffa"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableLookAround"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4a14c38-1749-4de2-a71e-835a4699e353"",
                    ""path"": ""<OculusTouchController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableLookAround"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bdba096-19fd-41da-908a-54cfa693a708"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinMaxUserInterface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""834251ca-cc67-4326-b1bf-43d95462d512"",
                    ""path"": ""<OculusTouchController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinMaxUserInterface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""093ac1c5-88c4-4e73-99ab-437f53e3942f"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinMaxUserInterface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18c1eebe-c637-4d97-bf75-a87dd77b645a"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinMaxDeveloperInterface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b083f82-63f1-4bbf-9732-e17a136bdc7e"",
                    ""path"": ""<OculusTouchController>{LeftHand}/{GripButton}"",
                    ""interactions"": ""Hold(duration=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MinMaxDeveloperInterface"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4dca370-9072-4c66-b35a-36563a6ef5b5"",
                    ""path"": ""<XRController>{RightHand}/{SecondaryButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttemptClearScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e979ab6e-c3e8-465a-907c-a97e114f4a6f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AttemptClearScene"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""id"": ""4b5aa0ac-00fa-4228-8313-c91d4344ee70"",
            ""actions"": [
                {
                    ""name"": ""PrimaryTouchStart"",
                    ""type"": ""Value"",
                    ""id"": ""288f46ba-6ac7-4fe4-9696-4cad4a149a8b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryTouchButton"",
                    ""type"": ""Button"",
                    ""id"": ""1b322d2f-26b3-44fa-b723-e6178877709d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTouchStart"",
                    ""type"": ""Value"",
                    ""id"": ""5b6f5dc4-99ad-4fd5-967d-008b8d0b7a3c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryTouchButton"",
                    ""type"": ""Button"",
                    ""id"": ""9580ce18-48bf-4454-aa25-78f2b603e371"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e9049a23-c9ac-40cc-848a-6f889b8ebdb8"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d6c36a6-3669-4293-b717-8123262c42bd"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouchButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97173816-ccda-4438-8cc0-e1dd8972ca5f"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6660d8f7-53b7-4f2f-b565-71feaac3280f"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Desktop"",
            ""id"": ""497f56e6-4c37-4583-93ce-7c78d330f49c"",
            ""actions"": [
                {
                    ""name"": ""Pan"",
                    ""type"": ""Value"",
                    ""id"": ""caf240ad-0b9e-4564-b8a0-b6162d3be920"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""a29f4dab-8982-465e-a5db-e2216115e576"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ToggleCulling"",
                    ""type"": ""Button"",
                    ""id"": ""ab0e29b6-6e20-4e21-85e2-00b09948d8ed"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Frame"",
                    ""type"": ""Button"",
                    ""id"": ""6c647fcf-6e30-4d64-b1af-2661a43fd96a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Orbit"",
                    ""type"": ""Value"",
                    ""id"": ""408000ee-34ad-469d-a0ef-4e23486ed75f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""0a7e10b3-565a-40e8-b11b-bd30808e24f7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LookAround"",
                    ""type"": ""Value"",
                    ""id"": ""ba7364f4-faa0-4ddf-8244-4a9f7def133b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Middle Mouse Drag"",
                    ""id"": ""57f8f46c-515f-4cf0-937d-59aeaf10b2e8"",
                    ""path"": ""OneModifier(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""d8c8d804-eb9e-4aa8-a380-1b7995ce9e9f"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""5579c1dd-ad50-4127-9125-6f92271a7275"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WSAD"",
                    ""id"": ""fcd7ca79-3b0c-45a3-a2c9-f53efa966a42"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""51c4a61c-2ab0-4b95-bede-d7feb8671482"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a175605f-21e1-4a32-8f93-745139c1faa4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bcc0fffc-c292-4336-8b78-70327e6ec867"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0e0cc2d1-9b1b-47e2-902f-d7a1fd28820d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7860307d-744c-4748-89a1-20dba335a4fc"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleCulling"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""618be3aa-1e65-4966-9507-3e3d058ab185"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Frame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""fa6f3c38-0c0c-4258-8fa5-a3189c00f9b5"",
                    ""path"": ""TwoModifiers(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Orbit"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""65e0f405-5149-4fb0-a33e-69abbb792cb9"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Orbit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""64c01196-515e-48bc-81f2-b2bd88762bf7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Orbit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""e58e4714-91f5-4f9d-9a18-b680dd6524bd"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Orbit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""a747805d-01c2-4efb-bf80-3e2b23a34a52"",
                    ""path"": ""TwoModifiers(overrideModifiersNeedToBePressedFirst=true)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""f396e943-a5f8-4752-905a-841b041aa2c7"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""3c1b69a6-c394-458a-80ca-3682e5374b8f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""024d259e-d3f7-46fc-98b5-755e01f47e70"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""4c0497d3-edea-43c5-969b-c40bfb4421a3"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=3,y=3)"",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""cb7620a3-6996-403a-8281-4f0fd225f39c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookAround"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e1594895-7508-4ce9-b1d3-5759716505be"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookAround"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""3a758f94-3edf-4e83-a7e3-cea80deb8f02"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookAround"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // XR
            m_XR = asset.FindActionMap("XR", throwIfNotFound: true);
            m_XR_Move = m_XR.FindAction("Move", throwIfNotFound: true);
            m_XR_LookAround = m_XR.FindAction("LookAround", throwIfNotFound: true);
            m_XR_EnableLookAround = m_XR.FindAction("EnableLookAround", throwIfNotFound: true);
            m_XR_MinMaxUserInterface = m_XR.FindAction("MinMaxUserInterface", throwIfNotFound: true);
            m_XR_MinMaxDeveloperInterface = m_XR.FindAction("MinMaxDeveloperInterface", throwIfNotFound: true);
            m_XR_AttemptClearScene = m_XR.FindAction("AttemptClearScene", throwIfNotFound: true);
            // Touch
            m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
            m_Touch_PrimaryTouchStart = m_Touch.FindAction("PrimaryTouchStart", throwIfNotFound: true);
            m_Touch_PrimaryTouchButton = m_Touch.FindAction("PrimaryTouchButton", throwIfNotFound: true);
            m_Touch_SecondaryTouchStart = m_Touch.FindAction("SecondaryTouchStart", throwIfNotFound: true);
            m_Touch_SecondaryTouchButton = m_Touch.FindAction("SecondaryTouchButton", throwIfNotFound: true);
            // Desktop
            m_Desktop = asset.FindActionMap("Desktop", throwIfNotFound: true);
            m_Desktop_Pan = m_Desktop.FindAction("Pan", throwIfNotFound: true);
            m_Desktop_Move = m_Desktop.FindAction("Move", throwIfNotFound: true);
            m_Desktop_ToggleCulling = m_Desktop.FindAction("ToggleCulling", throwIfNotFound: true);
            m_Desktop_Frame = m_Desktop.FindAction("Frame", throwIfNotFound: true);
            m_Desktop_Orbit = m_Desktop.FindAction("Orbit", throwIfNotFound: true);
            m_Desktop_Zoom = m_Desktop.FindAction("Zoom", throwIfNotFound: true);
            m_Desktop_LookAround = m_Desktop.FindAction("LookAround", throwIfNotFound: true);
        }

        ~@PlayerInputActions()
        {
            UnityEngine.Debug.Assert(!m_XR.enabled, "This will cause a leak and performance issues, PlayerInputActions.XR.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Touch.enabled, "This will cause a leak and performance issues, PlayerInputActions.Touch.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Desktop.enabled, "This will cause a leak and performance issues, PlayerInputActions.Desktop.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // XR
        private readonly InputActionMap m_XR;
        private List<IXRActions> m_XRActionsCallbackInterfaces = new List<IXRActions>();
        private readonly InputAction m_XR_Move;
        private readonly InputAction m_XR_LookAround;
        private readonly InputAction m_XR_EnableLookAround;
        private readonly InputAction m_XR_MinMaxUserInterface;
        private readonly InputAction m_XR_MinMaxDeveloperInterface;
        private readonly InputAction m_XR_AttemptClearScene;
        /// <summary>
        /// Provides access to input actions defined in input action map "XR".
        /// </summary>
        public struct XRActions
        {
            private @PlayerInputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public XRActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "XR/Move".
            /// </summary>
            public InputAction @Move => m_Wrapper.m_XR_Move;
            /// <summary>
            /// Provides access to the underlying input action "XR/LookAround".
            /// </summary>
            public InputAction @LookAround => m_Wrapper.m_XR_LookAround;
            /// <summary>
            /// Provides access to the underlying input action "XR/EnableLookAround".
            /// </summary>
            public InputAction @EnableLookAround => m_Wrapper.m_XR_EnableLookAround;
            /// <summary>
            /// Provides access to the underlying input action "XR/MinMaxUserInterface".
            /// </summary>
            public InputAction @MinMaxUserInterface => m_Wrapper.m_XR_MinMaxUserInterface;
            /// <summary>
            /// Provides access to the underlying input action "XR/MinMaxDeveloperInterface".
            /// </summary>
            public InputAction @MinMaxDeveloperInterface => m_Wrapper.m_XR_MinMaxDeveloperInterface;
            /// <summary>
            /// Provides access to the underlying input action "XR/AttemptClearScene".
            /// </summary>
            public InputAction @AttemptClearScene => m_Wrapper.m_XR_AttemptClearScene;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_XR; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="XRActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(XRActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="XRActions" />
            public void AddCallbacks(IXRActions instance)
            {
                if (instance == null || m_Wrapper.m_XRActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_XRActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @LookAround.started += instance.OnLookAround;
                @LookAround.performed += instance.OnLookAround;
                @LookAround.canceled += instance.OnLookAround;
                @EnableLookAround.started += instance.OnEnableLookAround;
                @EnableLookAround.performed += instance.OnEnableLookAround;
                @EnableLookAround.canceled += instance.OnEnableLookAround;
                @MinMaxUserInterface.started += instance.OnMinMaxUserInterface;
                @MinMaxUserInterface.performed += instance.OnMinMaxUserInterface;
                @MinMaxUserInterface.canceled += instance.OnMinMaxUserInterface;
                @MinMaxDeveloperInterface.started += instance.OnMinMaxDeveloperInterface;
                @MinMaxDeveloperInterface.performed += instance.OnMinMaxDeveloperInterface;
                @MinMaxDeveloperInterface.canceled += instance.OnMinMaxDeveloperInterface;
                @AttemptClearScene.started += instance.OnAttemptClearScene;
                @AttemptClearScene.performed += instance.OnAttemptClearScene;
                @AttemptClearScene.canceled += instance.OnAttemptClearScene;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="XRActions" />
            private void UnregisterCallbacks(IXRActions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @LookAround.started -= instance.OnLookAround;
                @LookAround.performed -= instance.OnLookAround;
                @LookAround.canceled -= instance.OnLookAround;
                @EnableLookAround.started -= instance.OnEnableLookAround;
                @EnableLookAround.performed -= instance.OnEnableLookAround;
                @EnableLookAround.canceled -= instance.OnEnableLookAround;
                @MinMaxUserInterface.started -= instance.OnMinMaxUserInterface;
                @MinMaxUserInterface.performed -= instance.OnMinMaxUserInterface;
                @MinMaxUserInterface.canceled -= instance.OnMinMaxUserInterface;
                @MinMaxDeveloperInterface.started -= instance.OnMinMaxDeveloperInterface;
                @MinMaxDeveloperInterface.performed -= instance.OnMinMaxDeveloperInterface;
                @MinMaxDeveloperInterface.canceled -= instance.OnMinMaxDeveloperInterface;
                @AttemptClearScene.started -= instance.OnAttemptClearScene;
                @AttemptClearScene.performed -= instance.OnAttemptClearScene;
                @AttemptClearScene.canceled -= instance.OnAttemptClearScene;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="XRActions.UnregisterCallbacks(IXRActions)" />.
            /// </summary>
            /// <seealso cref="XRActions.UnregisterCallbacks(IXRActions)" />
            public void RemoveCallbacks(IXRActions instance)
            {
                if (m_Wrapper.m_XRActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="XRActions.AddCallbacks(IXRActions)" />
            /// <seealso cref="XRActions.RemoveCallbacks(IXRActions)" />
            /// <seealso cref="XRActions.UnregisterCallbacks(IXRActions)" />
            public void SetCallbacks(IXRActions instance)
            {
                foreach (var item in m_Wrapper.m_XRActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_XRActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="XRActions" /> instance referencing this action map.
        /// </summary>
        public XRActions @XR => new XRActions(this);

        // Touch
        private readonly InputActionMap m_Touch;
        private List<ITouchActions> m_TouchActionsCallbackInterfaces = new List<ITouchActions>();
        private readonly InputAction m_Touch_PrimaryTouchStart;
        private readonly InputAction m_Touch_PrimaryTouchButton;
        private readonly InputAction m_Touch_SecondaryTouchStart;
        private readonly InputAction m_Touch_SecondaryTouchButton;
        /// <summary>
        /// Provides access to input actions defined in input action map "Touch".
        /// </summary>
        public struct TouchActions
        {
            private @PlayerInputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public TouchActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Touch/PrimaryTouchStart".
            /// </summary>
            public InputAction @PrimaryTouchStart => m_Wrapper.m_Touch_PrimaryTouchStart;
            /// <summary>
            /// Provides access to the underlying input action "Touch/PrimaryTouchButton".
            /// </summary>
            public InputAction @PrimaryTouchButton => m_Wrapper.m_Touch_PrimaryTouchButton;
            /// <summary>
            /// Provides access to the underlying input action "Touch/SecondaryTouchStart".
            /// </summary>
            public InputAction @SecondaryTouchStart => m_Wrapper.m_Touch_SecondaryTouchStart;
            /// <summary>
            /// Provides access to the underlying input action "Touch/SecondaryTouchButton".
            /// </summary>
            public InputAction @SecondaryTouchButton => m_Wrapper.m_Touch_SecondaryTouchButton;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Touch; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="TouchActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="TouchActions" />
            public void AddCallbacks(ITouchActions instance)
            {
                if (instance == null || m_Wrapper.m_TouchActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_TouchActionsCallbackInterfaces.Add(instance);
                @PrimaryTouchStart.started += instance.OnPrimaryTouchStart;
                @PrimaryTouchStart.performed += instance.OnPrimaryTouchStart;
                @PrimaryTouchStart.canceled += instance.OnPrimaryTouchStart;
                @PrimaryTouchButton.started += instance.OnPrimaryTouchButton;
                @PrimaryTouchButton.performed += instance.OnPrimaryTouchButton;
                @PrimaryTouchButton.canceled += instance.OnPrimaryTouchButton;
                @SecondaryTouchStart.started += instance.OnSecondaryTouchStart;
                @SecondaryTouchStart.performed += instance.OnSecondaryTouchStart;
                @SecondaryTouchStart.canceled += instance.OnSecondaryTouchStart;
                @SecondaryTouchButton.started += instance.OnSecondaryTouchButton;
                @SecondaryTouchButton.performed += instance.OnSecondaryTouchButton;
                @SecondaryTouchButton.canceled += instance.OnSecondaryTouchButton;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="TouchActions" />
            private void UnregisterCallbacks(ITouchActions instance)
            {
                @PrimaryTouchStart.started -= instance.OnPrimaryTouchStart;
                @PrimaryTouchStart.performed -= instance.OnPrimaryTouchStart;
                @PrimaryTouchStart.canceled -= instance.OnPrimaryTouchStart;
                @PrimaryTouchButton.started -= instance.OnPrimaryTouchButton;
                @PrimaryTouchButton.performed -= instance.OnPrimaryTouchButton;
                @PrimaryTouchButton.canceled -= instance.OnPrimaryTouchButton;
                @SecondaryTouchStart.started -= instance.OnSecondaryTouchStart;
                @SecondaryTouchStart.performed -= instance.OnSecondaryTouchStart;
                @SecondaryTouchStart.canceled -= instance.OnSecondaryTouchStart;
                @SecondaryTouchButton.started -= instance.OnSecondaryTouchButton;
                @SecondaryTouchButton.performed -= instance.OnSecondaryTouchButton;
                @SecondaryTouchButton.canceled -= instance.OnSecondaryTouchButton;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="TouchActions.UnregisterCallbacks(ITouchActions)" />.
            /// </summary>
            /// <seealso cref="TouchActions.UnregisterCallbacks(ITouchActions)" />
            public void RemoveCallbacks(ITouchActions instance)
            {
                if (m_Wrapper.m_TouchActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="TouchActions.AddCallbacks(ITouchActions)" />
            /// <seealso cref="TouchActions.RemoveCallbacks(ITouchActions)" />
            /// <seealso cref="TouchActions.UnregisterCallbacks(ITouchActions)" />
            public void SetCallbacks(ITouchActions instance)
            {
                foreach (var item in m_Wrapper.m_TouchActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_TouchActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="TouchActions" /> instance referencing this action map.
        /// </summary>
        public TouchActions @Touch => new TouchActions(this);

        // Desktop
        private readonly InputActionMap m_Desktop;
        private List<IDesktopActions> m_DesktopActionsCallbackInterfaces = new List<IDesktopActions>();
        private readonly InputAction m_Desktop_Pan;
        private readonly InputAction m_Desktop_Move;
        private readonly InputAction m_Desktop_ToggleCulling;
        private readonly InputAction m_Desktop_Frame;
        private readonly InputAction m_Desktop_Orbit;
        private readonly InputAction m_Desktop_Zoom;
        private readonly InputAction m_Desktop_LookAround;
        /// <summary>
        /// Provides access to input actions defined in input action map "Desktop".
        /// </summary>
        public struct DesktopActions
        {
            private @PlayerInputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public DesktopActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Desktop/Pan".
            /// </summary>
            public InputAction @Pan => m_Wrapper.m_Desktop_Pan;
            /// <summary>
            /// Provides access to the underlying input action "Desktop/Move".
            /// </summary>
            public InputAction @Move => m_Wrapper.m_Desktop_Move;
            /// <summary>
            /// Provides access to the underlying input action "Desktop/ToggleCulling".
            /// </summary>
            public InputAction @ToggleCulling => m_Wrapper.m_Desktop_ToggleCulling;
            /// <summary>
            /// Provides access to the underlying input action "Desktop/Frame".
            /// </summary>
            public InputAction @Frame => m_Wrapper.m_Desktop_Frame;
            /// <summary>
            /// Provides access to the underlying input action "Desktop/Orbit".
            /// </summary>
            public InputAction @Orbit => m_Wrapper.m_Desktop_Orbit;
            /// <summary>
            /// Provides access to the underlying input action "Desktop/Zoom".
            /// </summary>
            public InputAction @Zoom => m_Wrapper.m_Desktop_Zoom;
            /// <summary>
            /// Provides access to the underlying input action "Desktop/LookAround".
            /// </summary>
            public InputAction @LookAround => m_Wrapper.m_Desktop_LookAround;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Desktop; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="DesktopActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(DesktopActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="DesktopActions" />
            public void AddCallbacks(IDesktopActions instance)
            {
                if (instance == null || m_Wrapper.m_DesktopActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_DesktopActionsCallbackInterfaces.Add(instance);
                @Pan.started += instance.OnPan;
                @Pan.performed += instance.OnPan;
                @Pan.canceled += instance.OnPan;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @ToggleCulling.started += instance.OnToggleCulling;
                @ToggleCulling.performed += instance.OnToggleCulling;
                @ToggleCulling.canceled += instance.OnToggleCulling;
                @Frame.started += instance.OnFrame;
                @Frame.performed += instance.OnFrame;
                @Frame.canceled += instance.OnFrame;
                @Orbit.started += instance.OnOrbit;
                @Orbit.performed += instance.OnOrbit;
                @Orbit.canceled += instance.OnOrbit;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @LookAround.started += instance.OnLookAround;
                @LookAround.performed += instance.OnLookAround;
                @LookAround.canceled += instance.OnLookAround;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="DesktopActions" />
            private void UnregisterCallbacks(IDesktopActions instance)
            {
                @Pan.started -= instance.OnPan;
                @Pan.performed -= instance.OnPan;
                @Pan.canceled -= instance.OnPan;
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @ToggleCulling.started -= instance.OnToggleCulling;
                @ToggleCulling.performed -= instance.OnToggleCulling;
                @ToggleCulling.canceled -= instance.OnToggleCulling;
                @Frame.started -= instance.OnFrame;
                @Frame.performed -= instance.OnFrame;
                @Frame.canceled -= instance.OnFrame;
                @Orbit.started -= instance.OnOrbit;
                @Orbit.performed -= instance.OnOrbit;
                @Orbit.canceled -= instance.OnOrbit;
                @Zoom.started -= instance.OnZoom;
                @Zoom.performed -= instance.OnZoom;
                @Zoom.canceled -= instance.OnZoom;
                @LookAround.started -= instance.OnLookAround;
                @LookAround.performed -= instance.OnLookAround;
                @LookAround.canceled -= instance.OnLookAround;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="DesktopActions.UnregisterCallbacks(IDesktopActions)" />.
            /// </summary>
            /// <seealso cref="DesktopActions.UnregisterCallbacks(IDesktopActions)" />
            public void RemoveCallbacks(IDesktopActions instance)
            {
                if (m_Wrapper.m_DesktopActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="DesktopActions.AddCallbacks(IDesktopActions)" />
            /// <seealso cref="DesktopActions.RemoveCallbacks(IDesktopActions)" />
            /// <seealso cref="DesktopActions.UnregisterCallbacks(IDesktopActions)" />
            public void SetCallbacks(IDesktopActions instance)
            {
                foreach (var item in m_Wrapper.m_DesktopActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_DesktopActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="DesktopActions" /> instance referencing this action map.
        /// </summary>
        public DesktopActions @Desktop => new DesktopActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "XR" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="XRActions.AddCallbacks(IXRActions)" />
        /// <seealso cref="XRActions.RemoveCallbacks(IXRActions)" />
        public interface IXRActions
        {
            /// <summary>
            /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMove(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LookAround" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLookAround(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "EnableLookAround" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnEnableLookAround(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "MinMaxUserInterface" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMinMaxUserInterface(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "MinMaxDeveloperInterface" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMinMaxDeveloperInterface(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "AttemptClearScene" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAttemptClearScene(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Touch" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="TouchActions.AddCallbacks(ITouchActions)" />
        /// <seealso cref="TouchActions.RemoveCallbacks(ITouchActions)" />
        public interface ITouchActions
        {
            /// <summary>
            /// Method invoked when associated input action "PrimaryTouchStart" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPrimaryTouchStart(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "PrimaryTouchButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPrimaryTouchButton(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "SecondaryTouchStart" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSecondaryTouchStart(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "SecondaryTouchButton" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSecondaryTouchButton(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Desktop" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="DesktopActions.AddCallbacks(IDesktopActions)" />
        /// <seealso cref="DesktopActions.RemoveCallbacks(IDesktopActions)" />
        public interface IDesktopActions
        {
            /// <summary>
            /// Method invoked when associated input action "Pan" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnPan(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnMove(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "ToggleCulling" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnToggleCulling(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Frame" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnFrame(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Orbit" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnOrbit(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Zoom" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnZoom(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LookAround" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLookAround(InputAction.CallbackContext context);
        }
    }
}
